services:
  - type: web
    name: vibranium-nexus-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: NB
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
